name: nexa
description: A Voice assistant app for android head units.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.4.1
  vosk_flutter: ^0.3.48
  connectivity_plus: ^5.0.1
  flutter_phone_direct_caller: ^2.1.1
  flutter_contacts: ^1.1.7+1
  fluttertoast: ^8.2.4
  map_launcher: ^3.1.0
  call_log: ^4.0.0
  device_installed_apps: ^1.0.1
  volume_regulator: ^2.2.0
  flutter_tts: ^3.8.3
  dash_bubble: ^2.0.0
  fuzzywuzzy: ^1.1.6
  permission_handler: ^10.4.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/geoLocation.json